version: "3.8"

services:
  app:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - ./.env # Loads variables from the .env file
    depends_on:
      - mongodb
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: