# docker-compose.yml

version: "3.8"

services:
  app:
    build: .
    ports:
      - "5000:5000" # Map port 5000 on the server to port 5000 in the container
    env_file:
      - ./.env      # Load environment variables from the .env file
    restart: unless-stopped